# Generated by Django 2.0.13 on 2019-08-21 15:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160418_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.IntegerField(choices=[(1, 'Borrador'), (2, 'Published')], default=2, verbose_name='Status'),
        ),
    ]
