# Generated by Django 2.0.13 on 2019-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190821_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='flyer',
            field=models.ImageField(blank=True, default='', null=True, upload_to='flyers'),
        ),
    ]
