# Generated by Django 2.0.13 on 2019-08-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('forms', '0004_form_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='evento',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Evento'),
        ),
    ]
