# Generated by Django 2.0.13 on 2019-08-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='titulo_boton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
